### ISSUE TITLE
Bug: Incorrect total return for holding

### ISSUE THREAD

**Issue by Citrus0299** [we-promise/sure#500]
### General checklist

- [X] I have removed personal / sensitive data from screenshots and logs
- [X] I have searched [existing issues](https://github.com/we-promise/sure/issues?q=is:issue) and [discussions](https://github.com/we-promise/sure/discussions) to ensure this is not a duplicate issue
    
### How are you using Sure?

- [ ] I was a paying Maybe customer (hosted version)
- [ ] I use it on PikaPod, Umbrel or similar (VPS included)
- [X] I am a self-hosted user (local only)

### Self hoster checklist

_Paying, hosted users should delete this entire section._

If you are a self-hosted user, please complete all of the information below.  Issues with incomplete information will be marked as `Needs Info` to help our small team prioritize bug fixes.

- Self hosted app commit SHA (find in user menu): `664c6c2`
  - [X] I have confirmed that my app's commit is the latest version of Sure
- Where are you hosting?
  - [ ] Render
  - [X] Docker Compose
  - [ ] Umbrel
  - [ ] PikaPod
  - [ ] Other (please specify)

---

## Bug description

I am currently investigating the financial accuracy of sure compared to another OSS Portfolio tracker called Ghostfolio. My self hosted Ghostfolio Instance has 400+ stock transactions tracked.

All I am looking for is a simple ROI performance calculation of a single stock in sure.
Therefore I converted a Ghostfolio export to a sure CSV and imported it. I am using the same dataprovider as Ghostfolio, yahoo finance.

<img width="526" height="287" alt="Image" src="https://github.com/user-attachments/assets/5380c72b-06df-4a22-858c-843804e0d96e" />

The first thing I noticed is that the current market price is outdated (Sever is running 24/7).
Sure: 36.50 €
Broker: 38.6577 €
Yahoo: 38.62 €

The more frustrating thing is that the total performance is also not even close to accurate:
Sure: 198.72 € / 4.9 %
Broker: 452.25 € / 11.05 %

You will find Buys with a 0 € order price in the csv because this fund returns dividend as stock. This is not a bug in the import!

### To Reproduce

Be as specific as possible so Sure contributors can quickly reproduce the bug you're experiencing.

1. Import the following csv into an investment account
```csv
date*,ticker*,exchange_operating_mic,currency,qty*,price*,account,name
05/16/2023,ELFW.DE,XETR,EUR,1.867,26.78687,Deka,ELFW.DE Buy
06/15/2023,ELFW.DE,XETR,EUR,0.009,0,Deka,ELFW.DE Buy
06/16/2023,ELFW.DE,XETR,EUR,1.795,27.86061,Deka,ELFW.DE Buy
07/18/2023,ELFW.DE,XETR,EUR,1.806,27.68788,Deka,ELFW.DE Buy
08/16/2023,ELFW.DE,XETR,EUR,1.792,27.89596,Deka,ELFW.DE Buy
09/14/2023,ELFW.DE,XETR,EUR,0.017,0,Deka,ELFW.DE Buy
09/18/2023,ELFW.DE,XETR,EUR,1.746,28.63939,Deka,ELFW.DE Buy
10/17/2023,ELFW.DE,XETR,EUR,1.77,28.24647,Deka,ELFW.DE Buy
11/16/2023,ELFW.DE,XETR,EUR,1.765,28.32626,Deka,ELFW.DE Buy
12/14/2023,ELFW.DE,XETR,EUR,0.032,0,Deka,ELFW.DE Buy
12/18/2023,ELFW.DE,XETR,EUR,1.694,29.51111,Deka,ELFW.DE Buy
01/16/2024,ELFW.DE,XETR,EUR,1.679,29.77374,Deka,ELFW.DE Buy
02/02/2024,ELFW.DE,XETR,EUR,-0.246,30.166,Deka,ELFW.DE Sell
02/16/2024,ELFW.DE,XETR,EUR,1.589,31.4596,Deka,ELFW.DE Buy
03/14/2024,ELFW.DE,XETR,EUR,0.018,0,Deka,ELFW.DE Buy
03/18/2024,ELFW.DE,XETR,EUR,1.569,31.86566,Deka,ELFW.DE Buy
04/16/2024,ELFW.DE,XETR,EUR,1.535,32.57475,Deka,ELFW.DE Buy
05/16/2024,ELFW.DE,XETR,EUR,1.514,33.01616,Deka,ELFW.DE Buy
06/13/2024,ELFW.DE,XETR,EUR,0.106,0,Deka,ELFW.DE Buy
06/18/2024,ELFW.DE,XETR,EUR,1.487,33.62121,Deka,ELFW.DE Buy
07/16/2024,ELFW.DE,XETR,EUR,1.452,34.43838,Deka,ELFW.DE Buy
08/16/2024,ELFW.DE,XETR,EUR,1.491,33.52929,Deka,ELFW.DE Buy
09/13/2024,ELFW.DE,XETR,EUR,0.072,0,Deka,ELFW.DE Buy
09/17/2024,ELFW.DE,XETR,EUR,1.485,33.66869,Deka,ELFW.DE Buy
10/16/2024,ELFW.DE,XETR,EUR,1.413,35.38586,Deka,ELFW.DE Buy
11/18/2024,ELFW.DE,XETR,EUR,1.375,36.35758,Deka,ELFW.DE Buy
12/13/2024,ELFW.DE,XETR,EUR,0.074,0,Deka,ELFW.DE Buy
12/17/2024,ELFW.DE,XETR,EUR,1.331,37.56869,Deka,ELFW.DE Buy
01/14/2025,ELFW.DE,XETR,EUR,67.677,36.9404,Deka,ELFW.DE Buy
01/16/2025,ELFW.DE,XETR,EUR,1.335,37.45657,Deka,ELFW.DE Buy
02/18/2025,ELFW.DE,XETR,EUR,1.298,38.50707,Deka,ELFW.DE Buy
03/13/2025,ELFW.DE,XETR,EUR,0.15,0,Deka,ELFW.DE Buy
03/18/2025,ELFW.DE,XETR,EUR,1.437,34.80101,Deka,ELFW.DE Buy
04/14/2025,ELFW.DE,XETR,EUR,1.549,32.28,Deka,ELFW.DE Buy
05/14/2025,ELFW.DE,XETR,EUR,1.408,35.5,Deka,ELFW.DE Buy
06/11/2025,ELFW.DE,XETR,EUR,0.524,0,Deka,ELFW.DE Buy
06/15/2025,ELFW.DE,XETR,EUR,1.425,35.09,Deka,ELFW.DE Buy
07/14/2025,ELFW.DE,XETR,EUR,1.392,35.93,Deka,ELFW.DE Buy
08/14/2025,ELFW.DE,XETR,EUR,1.358,36.82,Deka,ELFW.DE Buy
09/11/2025,ELFW.DE,XETR,EUR,0.241,0,Deka,ELFW.DE Buy
09/14/2025,ELFW.DE,XETR,EUR,1.335,37.44,Deka,ELFW.DE Buy
10/14/2025,ELFW.DE,XETR,EUR,1.308,38.22,Deka,ELFW.DE Buy
11/16/2025,ELFW.DE,XETR,EUR,1.297,38.54,Deka,ELFW.DE Buy
12/11/2025,ELFW.DE,XETR,EUR,0.273,0,Deka,ELFW.DE Buy
12/14/2025,ELFW.DE,XETR,EUR,1.293,38.68,Deka,ELFW.DE Buy
```

2. Go to Home -> Investment -> "Deka" Account
3. Click on the Holdings tab and select the ELFW.DE Holding (The total number of shares should be 117.5)
4. Check the performance.

### Expected behavior

1. The current stock value should match yahoo
2. The performance should match a standard ROI performance calculation (close to the broker reported 452.25 +11.05%) or it should be clearly stated that a different performance metric is being used.

### Screenshots and/or recordings

We highly recommend providing additional context with screenshots and/or screen recordings.  This will _significantly_ improve the chances of the bug being addressed and fixed quickly.

**Comment by jjmata** [comment]
This is amazing work to help us improve the investments area, @Citrus0299!  Thank you.

Putting this on @sokie's radar who's been looking at it already.

**Comment by Citrus0299** [comment]
Thank you for taking this issue seriously.

This bug might be a bit more nuanced than I initially thought. After setting up a new instance and directly importing after setup, the reported performance was correct. However after a few days just letting it sit, sure reports -€980.41 (-24.0%).

So I checked the database for the stored security data:

```sql
SELECT * FROM "securities" WHERE "ticker"='ELFW.DE';
```
```
                  id                  | ticker  | name |         created_at         |         updated_at         | country_code | exchange_mic | exchange_acronym | logo_url | exchange_operating_mic | offline | failed_fetch_at | failed_fetch_count |    last_health_check_at    
--------------------------------------+---------+------+----------------------------+----------------------------+--------------+--------------+------------------+----------+------------------------+---------+-----------------+--------------------+----------------------------
 e36ba75a-c33f-4907-8242-f59f1b1deba1 | ELFW.DE |      | 2025-12-24 13:38:22.735304 | 2025-12-25 02:00:05.543887 | DE           |              |                  |          | GER                    | f       |                 |                  0 | 2025-12-25 02:00:05.540481
```

```sql
SELECT * FROM "security_prices" WHERE "security_id"='e36ba75a-c33f-4907-8242-f59f1b1deba1' ORDER BY "created_at" DESC;
```
```
                   id                  |    date    |  price  | currency |         created_at         |         updated_at         |             security_id              
 --------------------------------------+------------+---------+----------+----------------------------+----------------------------+--------------------------------------
  6664511d-aa4e-4f3e-ad87-f2608d38c12f | 2025-12-28 | 26.4680 | EUR      | 2025-12-28 02:22:11.833652 | 2025-12-28 02:22:11.833652 | e36ba75a-c33f-4907-8242-f59f1b1deba1
  707089bf-a130-4047-a770-028a55b1c923 | 2025-12-27 | 26.4680 | EUR      | 2025-12-27 02:22:15.273198 | 2025-12-27 02:22:15.273198 | e36ba75a-c33f-4907-8242-f59f1b1deba1
  f80e2f29-1d21-4cfd-be1d-3d38f161ca07 | 2025-12-26 | 26.4680 | EUR      | 2025-12-26 02:22:05.210708 | 2025-12-26 02:22:05.210708 | e36ba75a-c33f-4907-8242-f59f1b1deba1
  faf3f374-cadb-413d-bac9-b80cb0746bc1 | 2025-12-25 | 26.4680 | EUR      | 2025-12-25 02:22:27.167454 | 2025-12-25 02:22:27.167454 | e36ba75a-c33f-4907-8242-f59f1b1deba1
  277d407f-3fa7-434c-8d34-3ea4c843282b | 2025-11-13 | 38.3730 | EUR      | 2025-12-24 13:38:23.17084  | 2025-12-24 13:38:23.17084  | e36ba75a-c33f-4907-8242-f59f1b1deba1
  80584596-de5e-4ffa-87b1-5c5a786fe9fe | 2025-11-12 | 38.9040 | EUR      | 2025-12-24 13:38:23.17084  | 2025-12-24 13:38:23.17084  | e36ba75a-c33f-4907-8242-f59f1b1deba1
```

So the initially fetched historical data is correct. However the newly fetched market price fetched every day is wrong.
I hope this makes the issue more reproducible and increases it's priority since at least the yahoo data provider is polluting instances with false market data.

**Comment by sokie** [comment]
> Thank you for taking this issue seriously.
> 
> This bug might be a bit more nuanced than I initially thought. After setting up a new instance and directly importing after setup, the reported performance was correct. However after a few days just letting it sit, sure reports -€980.41 (-24.0%).
> 
> So I checked the database for the stored security data:
> 
> SELECT * FROM "securities" WHERE "ticker"='ELFW.DE';
> ```
>                   id                  | ticker  | name |         created_at         |         updated_at         | country_code | exchange_mic | exchange_acronym | logo_url | exchange_operating_mic | offline | failed_fetch_at | failed_fetch_count |    last_health_check_at    
> --------------------------------------+---------+------+----------------------------+----------------------------+--------------+--------------+------------------+----------+------------------------+---------+-----------------+--------------------+----------------------------
>  e36ba75a-c33f-4907-8242-f59f1b1deba1 | ELFW.DE |      | 2025-12-24 13:38:22.735304 | 2025-12-25 02:00:05.543887 | DE           |              |                  |          | GER                    | f       |                 |                  0 | 2025-12-25 02:00:05.540481
> ```
> 
> SELECT * FROM "security_prices" WHERE "security_id"='e36ba75a-c33f-4907-8242-f59f1b1deba1' ORDER BY "created_at" DESC;
> ```
>                    id                  |    date    |  price  | currency |         created_at         |         updated_at         |             security_id              
>  --------------------------------------+------------+---------+----------+----------------------------+----------------------------+--------------------------------------
>   6664511d-aa4e-4f3e-ad87-f2608d38c12f | 2025-12-28 | 26.4680 | EUR      | 2025-12-28 02:22:11.833652 | 2025-12-28 02:22:11.833652 | e36ba75a-c33f-4907-8242-f59f1b1deba1
>   707089bf-a130-4047-a770-028a55b1c923 | 2025-12-27 | 26.4680 | EUR      | 2025-12-27 02:22:15.273198 | 2025-12-27 02:22:15.273198 | e36ba75a-c33f-4907-8242-f59f1b1deba1
>   f80e2f29-1d21-4cfd-be1d-3d38f161ca07 | 2025-12-26 | 26.4680 | EUR      | 2025-12-26 02:22:05.210708 | 2025-12-26 02:22:05.210708 | e36ba75a-c33f-4907-8242-f59f1b1deba1
>   faf3f374-cadb-413d-bac9-b80cb0746bc1 | 2025-12-25 | 26.4680 | EUR      | 2025-12-25 02:22:27.167454 | 2025-12-25 02:22:27.167454 | e36ba75a-c33f-4907-8242-f59f1b1deba1
>   277d407f-3fa7-434c-8d34-3ea4c843282b | 2025-11-13 | 38.3730 | EUR      | 2025-12-24 13:38:23.17084  | 2025-12-24 13:38:23.17084  | e36ba75a-c33f-4907-8242-f59f1b1deba1
>   80584596-de5e-4ffa-87b1-5c5a786fe9fe | 2025-11-12 | 38.9040 | EUR      | 2025-12-24 13:38:23.17084  | 2025-12-24 13:38:23.17084  | e36ba75a-c33f-4907-8242-f59f1b1deba1
> ```
> 
> So the initially fetched historical data is correct. However the newly fetched market price fetched every day is wrong. I hope this makes the issue more reproducible and increases it's priority since at least the yahoo data provider is polluting instances with false market data.

While we don't have control over third party providers, i did see this myself a couple of times with yahoo. I've already fixed an issue where Yahoo doesn't have a stock price over the weekend, and instead of returning last k own price would return complete crap, so now i do carry forward price over gaps.  
But myself I completely switched to Twelvedata for securities tbh.  
I will pick this up as i do a small revamp of investments and will check!

**Comment by Citrus0299** [comment]
The thing is that ghostfolio is also using yahoo and the data is correct there.

If I understand the twelvedata pricing structure correctly I would have to pay $290 a year for XETR stocks

**Comment by sergifs** [comment]
Hello, I noticed the same issue and identified a pattern that might help with the investigation.
I have an investment account with 2 tickers connected to Yahoo Finance:
|id|ticker|
|--|------|
|a738a52b-d01b-4291-b018-932eab2bdd4b|0P00000X1Y.F|
|dbb01f40-db3e-4101-ab67-a7fe3f4a49d2|0P0000X6HY.F|

Upon creation, all automatically retrieved data was accurate. However, the next day (07/01/2026), it reported an incorrect value for each. Even after syncing again, the values didn't change despite Yahoo Finance showing the correct data. I had to manually delete the rows in Postgres and sync again to retrieve the correct values.

Today (08/01/2026), the same thing happened. Coincidentally, the incorrect values received today match the incorrect ones from yesterday, which are the exact same prices the tickers had on the day I bought them (18/11/2025).

|date|price|currency|security_id|
|----|-----|--------|-----------|
|08/01/2026|118.4300|EUR|a738a52b-d01b-4291-b018-932eab2bdd4b|
|07/01/2026|129.5800|EUR|a738a52b-d01b-4291-b018-932eab2bdd4b|
|18/11/2025|118.4300|EUR|a738a52b-d01b-4291-b018-932eab2bdd4b|
|08/01/2026|38.3617|EUR|dbb01f40-db3e-4101-ab67-a7fe3f4a49d2|
|07/01/2026|40.8780|EUR|dbb01f40-db3e-4101-ab67-a7fe3f4a49d2|
|18/11/2025|38.3617|EUR|dbb01f40-db3e-4101-ab67-a7fe3f4a49d2|

At this moment, one of the tickers already shows the close price for today on Yahoo Finance, but syncing in SURE doesn't update the record.
It appears that SURE creates the "today" rows in table "security_prices", but if it doesn't receive data from the provider immediately, it defaults to the value from the purchase date. Once that row exists, it seems to be treated as legitimate and isn't overwritten when correct data becomes available.

**Comment by sokie** [comment]
> Hello, I noticed the same issue and identified a pattern that might help with the investigation. I have an investment account with 2 tickers connected to Yahoo Finance:
> 
> id	ticker
> a738a52b-d01b-4291-b018-932eab2bdd4b	0P00000X1Y.F
> dbb01f40-db3e-4101-ab67-a7fe3f4a49d2	0P0000X6HY.F
> Upon creation, all automatically retrieved data was accurate. However, the next day (07/01/2026), it reported an incorrect value for each. Even after syncing again, the values didn't change despite Yahoo Finance showing the correct data. I had to manually delete the rows in Postgres and sync again to retrieve the correct values.
> 
> Today (08/01/2026), the same thing happened. Coincidentally, the incorrect values received today match the incorrect ones from yesterday, which are the exact same prices the tickers had on the day I bought them (18/11/2025).
> 
> date	price	currency	security_id
> 08/01/2026	118.4300	EUR	a738a52b-d01b-4291-b018-932eab2bdd4b
> 07/01/2026	129.5800	EUR	a738a52b-d01b-4291-b018-932eab2bdd4b
> 18/11/2025	118.4300	EUR	a738a52b-d01b-4291-b018-932eab2bdd4b
> 08/01/2026	38.3617	EUR	dbb01f40-db3e-4101-ab67-a7fe3f4a49d2
> 07/01/2026	40.8780	EUR	dbb01f40-db3e-4101-ab67-a7fe3f4a49d2
> 18/11/2025	38.3617	EUR	dbb01f40-db3e-4101-ab67-a7fe3f4a49d2
> At this moment, one of the tickers already shows the close price for today on Yahoo Finance, but syncing in SURE doesn't update the record. It appears that SURE creates the "today" rows in table "security_prices", but if it doesn't receive data from the provider immediately, it defaults to the value from the purchase date. Once that row exists, it seems to be treated as legitimate and isn't overwritten when correct data becomes available.

Thanks for this and your analysis is absolutely spot on. Sure would carry over the price and never retrieve the live price anymore..
This was fixed just now in https://github.com/we-promise/sure/pull/559
A new hotfix release should land soon with it!

**Comment by sergifs** [comment]
Thank you @sokie, I installed the latest alpha and tested the new logic. After manually marking both rows as provisional = true and refreshing, the ticker with an available price for today was correctly updated and the provisional flag cleared. The other ticker correctly remains marked as provisional while waiting for Yahoo Finance to provide a price.

Just a heads-up: to successfully toggle the provisional boolean, I had to manually create a UK constraint on (security_id, date). Without it, PG threw the error "Attribute provisional was changed but it hasn't associated unique key".

**Comment by Citrus0299** [comment]
@sokie So manual user intervention is required to fix the issue for existing data?

**Comment by sokie** [comment]
> [@sokie](https://github.com/sokie) So manual user intervention is required to fix the issue for existing data?

I'll check the UK issue.
@Citrus0299 no, provisional prices will be automatically handled and we will try to fetch real prices for up to 3 days before giving up and re-using past day prices.

**Comment by sokie** [comment]
@Citrus0299 the UK issue is expected if trying to manually toggle, since we have a UK `[security_id, date, currency]`.
This is correctly handled in the application by doing upsert_all in the importer that correctly uses unique_by: %i[security_id date currency] (importer.rb:186).
If you want to manually upsert, you can always use `Security::Price.where(id: id).update_all(provisional: true)` on the cmdline.

**Comment by Citrus0299** [comment]
I don't think [v0.6.7-alpha.3](https://github.com/we-promise/sure/releases/tag/v0.6.7-alpha.3) resolved this issue.
The market price fetched overnight is still wrong.

**Comment by Citrus0299** [comment]
```
                  id                  |    date    |  price  | currency |         created_at         |         updated_at         |             security_id              | provisional 
--------------------------------------+------------+---------+----------+----------------------------+----------------------------+--------------------------------------+-------------
 481ab958-a9a9-4cf8-a1a3-4d962bee1457 | 2026-01-10 | 26.4680 | EUR      | 2026-01-10 02:22:20.680912 | 2026-01-10 02:22:20.68044  | e36ba75a-c33f-4907-8242-f59f1b1deba1 | f
 8f7ce298-b648-4b1e-853c-5f30c0c7b642 | 2026-01-09 | 39.3420 | EUR      | 2026-01-09 08:42:31.748051 | 2026-01-09 08:42:31.706187 | e36ba75a-c33f-4907-8242-f59f1b1deba1 | f
 7665a44c-c676-4fbc-b0f3-5fbe4a99cbf7 | 2026-01-08 | 39.2310 | EUR      | 2026-01-09 08:42:31.748051 | 2026-01-09 08:42:31.706187 | e36ba75a-c33f-4907-8242-f59f1b1deba1 | f
 4a847da3-5c0f-4841-861f-6bcdbc40ba28 | 2026-01-07 | 39.3060 | EUR      | 2026-01-09 08:42:31.748051 | 2026-01-09 08:42:31.706187 | e36ba75a-c33f-4907-8242-f59f1b1deba1 | f
 a396348f-0f1a-493d-82f0-fa172e66c508 | 2026-01-06 | 39.1800 | EUR      | 2026-01-09 08:42:31.748051 | 2026-01-09 08:42:31.706187 | e36ba75a-c33f-4907-8242-f59f1b1deba1 | f
```

**Comment by sokie** [comment]
> ```
>                   id                  |    date    |  price  | currency |         created_at         |         updated_at         |             security_id              | provisional 
> --------------------------------------+------------+---------+----------+----------------------------+----------------------------+--------------------------------------+-------------
>  481ab958-a9a9-4cf8-a1a3-4d962bee1457 | 2026-01-10 | 26.4680 | EUR      | 2026-01-10 02:22:20.680912 | 2026-01-10 02:22:20.68044  | e36ba75a-c33f-4907-8242-f59f1b1deba1 | f
>  8f7ce298-b648-4b1e-853c-5f30c0c7b642 | 2026-01-09 | 39.3420 | EUR      | 2026-01-09 08:42:31.748051 | 2026-01-09 08:42:31.706187 | e36ba75a-c33f-4907-8242-f59f1b1deba1 | f
>  7665a44c-c676-4fbc-b0f3-5fbe4a99cbf7 | 2026-01-08 | 39.2310 | EUR      | 2026-01-09 08:42:31.748051 | 2026-01-09 08:42:31.706187 | e36ba75a-c33f-4907-8242-f59f1b1deba1 | f
>  4a847da3-5c0f-4841-861f-6bcdbc40ba28 | 2026-01-07 | 39.3060 | EUR      | 2026-01-09 08:42:31.748051 | 2026-01-09 08:42:31.706187 | e36ba75a-c33f-4907-8242-f59f1b1deba1 | f
>  a396348f-0f1a-493d-82f0-fa172e66c508 | 2026-01-06 | 39.1800 | EUR      | 2026-01-09 08:42:31.748051 | 2026-01-09 08:42:31.706187 | e36ba75a-c33f-4907-8242-f59f1b1deba1 | f
> ```

Thanks for the logs, can you share the stock tickers also please, and which provider you are using?( yahoo or Twelve data ).
Ill look into it and check!

**Comment by Citrus0299** [comment]
Still the same ticker `ELFW.DE` and yahoo as the provider. I can't use twelve data without a subscription.

**Comment by sokie** [comment]
> Still the same ticker `ELFW.DE` and yahoo as the provider. I can't use twelve data without a subscription.

Thanks, ill look into it today!

**Comment by sokie** [comment]
@Citrus0299 found the issue, fix is in https://github.com/we-promise/sure/pull/600
analysis:
1. A sync runs before the market opens (02:22 UTC for XETRA which opens at 08:00 UTC)
2. Yahoo returns no price for the current day
3. The importer gap-fills using start_price_value
4. start_price_value looks for prices <= the first trade date (possibly years ago)
5. When no provider prices exist for that old date, it falls back to a stale DB price
6. This stale price (26.4680 - the original purchase price) gets used and marked as non-provisional

An edge case on logic for provisional flag mixed with weekend logic made the code fallback to wrong first date trade.

**Comment by sokie** [comment]
@Citrus0299 we released a new alpha 6, which includes PR https://github.com/we-promise/sure/pull/600
if you can test, please do let me know.

**Comment by Citrus0299** [comment]
Thanks for the ping, I updated my instance yesterday. It looks like the issue has been resolved now.
I will check again in a few days, since it's still the weekend and the stock prize is still the same as friday.

**Comment by sokie** [comment]
> Thanks for the ping, I updated my instance yesterday. It looks like the issue has been resolved now. I will check again in a few days, since it's still the weekend and the stock prize is still the same as friday.

Thanks, let me know!
And yes, the provider doesnt return price for the weekend in the api, so Monday it should update.
